package EAHibernate;
// Generated 07-feb-2018 10:21:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Developers generated by hbm2java
 */
public class Developers  implements java.io.Serializable {


     private Integer id;
     private String idCard;
     private String name;
     private String surname;
     private float salary;
     private String job;
     private String country;
     private Set<Develops> developses = new HashSet<Develops>(0);

    public Developers() {
    }

	
    public Developers(String idCard, String name, String surname, float salary, String job, String country) {
        this.idCard = idCard;
        this.name = name;
        this.surname = surname;
        this.salary = salary;
        this.job = job;
        this.country = country;
    }
    public Developers(String idCard, String name, String surname, float salary, String job, String country, Set<Develops> developses) {
       this.idCard = idCard;
       this.name = name;
       this.surname = surname;
       this.salary = salary;
       this.job = job;
       this.country = country;
       this.developses = developses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public float getSalary() {
        return this.salary;
    }
    
    public void setSalary(float salary) {
        this.salary = salary;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<Develops> getDevelopses() {
        return this.developses;
    }
    
    public void setDevelopses(Set<Develops> developses) {
        this.developses = developses;
    }




}


