package EAHibernate;
// Generated 07-feb-2018 10:21:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Divisions generated by hbm2java
 */
public class Divisions  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Studios> studioses = new HashSet<Studios>(0);

    public Divisions() {
    }

	
    public Divisions(String name) {
        this.name = name;
    }
    public Divisions(String name, Set<Studios> studioses) {
       this.name = name;
       this.studioses = studioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Studios> getStudioses() {
        return this.studioses;
    }
    
    public void setStudioses(Set<Studios> studioses) {
        this.studioses = studioses;
    }




}


