package EAHibernate;
// Generated 07-feb-2018 10:21:04 by Hibernate Tools 4.3.1


import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.query.Query;

import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import static EAHibernate.HibernateTools.getSessionFactory;

/**
 * Games generated by hbm2java
 */
public class Games  implements java.io.Serializable {


     private Integer id;
     private Franchises franchises;
     private String name;
     private String genre;
     private float price;
     private Set<Develops> developses = new HashSet<Develops>(0);
     private Set<Sales> saleses = new HashSet<Sales>(0);

    public Games() {
    }

	
    public Games(String name, String genre, float price) {
        this.name = name;
        this.genre = genre;
        this.price = price;
    }
    public Games(Franchises franchises, String name, String genre, float price, Set<Develops> developses, Set<Sales> saleses) {
       this.franchises = franchises;
       this.name = name;
       this.genre = genre;
       this.price = price;
       this.developses = developses;
       this.saleses = saleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Franchises getFranchises() {
        return this.franchises;
    }
    
    public void setFranchises(Franchises franchises) {
        this.franchises = franchises;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public Set<Develops> getDevelopses() {
        return this.developses;
    }
    
    public void setDevelopses(Set<Develops> developses) {
        this.developses = developses;
    }
    public Set<Sales> getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set<Sales> saleses) {
        this.saleses = saleses;
    }


    //Methods
    public static void insertGame(String name, String genre, Float price, int fid){
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Transaction t = s.beginTransaction();
        Games g = new Games();
        g.setName(name);
        g.setGenre(genre);
        g.setPrice(price);
        g.setFranchiseId(fid);
        s.save(g);
        t.commit();

    }
    public static void printGames(){
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Query q = s.createQuery("from Games ");
        List results = q.list();
        Iterator iterator = results.iterator();
        System.out.println("NAME\t|\t GENRE\t|\t PRICE\t|\t FRANCHISE\t\t |");
        while (iterator.hasNext()){
            Games game = (Games) iterator.next();
            System.out.println(game.getName() + "\t\t"+game.getGenre()+"\t\t"+game.franchisesByFranchiseId.getName());

        }
    }
    public static void updateGames(int id, String newName, String newGenre, float newPrice, int newFranchise){
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Transaction t = s.beginTransaction();
    }

    //TODO:Algo va mal
    Games game = new Games();

        game.setName(newName);
        game.setGenre(newGenre);
        game.setPrice(newPrice);
        game.setFranchiseId(newFranchise);
        s.update(game);
        t.commit();
        s.close();
        sf.close();
}
    public static void deleteGames(int id){
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Transaction t = s.beginTransaction();

        Games g = new Games(id);
        s.delete(g);
        t.commit();
        s.close();
    }

}


}


