package EAHibernate;
// Generated 07-feb-2018 10:21:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sales generated by hbm2java
 */
public class Sales  implements java.io.Serializable {


     private Integer id;
     private Clients clients;
     private Games games;
     private int quantity;
     private Date date;

    public Sales() {
    }

	
    public Sales(int quantity) {
        this.quantity = quantity;
    }
    public Sales(Clients clients, Games games, int quantity, Date date) {
       this.clients = clients;
       this.games = games;
       this.quantity = quantity;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Games getGames() {
        return this.games;
    }
    
    public void setGames(Games games) {
        this.games = games;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


