package EAHibernate;
// Generated 07-feb-2018 10:21:04 by Hibernate Tools 4.3.1


import EA.Read;
import EA.Studio;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.query.Query;

import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import static EAHibernate.HibernateTools.getSessionFactory;

/**
 * Studios generated by hbm2java
 */
public class Studios  implements java.io.Serializable {


     private Integer id;
     private Divisions divisions;
     private String name;
     private String country;
     private Set<Franchises> franchiseses = new HashSet<Franchises>(0);

    public Studios() {
    }

	
    public Studios(String name, String country) {
        this.name = name;
        this.country = country;
    }
    public Studios(Divisions divisions, String name, String country, Set<Franchises> franchiseses) {
       this.divisions = divisions;
       this.name = name;
       this.country = country;
       this.franchiseses = franchiseses;
    }

    public Studios(int anInt) {
        id = anInt;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Divisions getDivisions() {
        return this.divisions;
    }
    
    public void setDivisions(Divisions divisions) {
        this.divisions = divisions;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<Franchises> getFranchiseses() {
        return this.franchiseses;
    }
    
    public void setFranchiseses(Set<Franchises> franchiseses) {
        this.franchiseses = franchiseses;
    }

    //Methods
    public static void insertStudio() {

        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Transaction t = s.beginTransaction();
        Studios st = new Studios();
        st.setId(1);
        st.setName(Read.String("Name: "));
        st.setCountry(Read.String("Country: "));
        st.setDivisions(new Divisions(Read.Int("Division ID:")));

        s.save(st);
        t.commit();
        s.close();


    }

    public static void printStudios() {
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Query q = s.createQuery("from Studios ");
        List results = q.list();
        Iterator iterator = results.iterator();
        System.out.println("NAME\t|\t COUNTRY\t|\t DIVISION\t|");
        System.out.println("-------------------------------------------------");
        while (iterator.hasNext()) {
            Studios st = (Studios) iterator.next();
            System.out.println(st.getName() + "\t\t" + st.getCountry() + "\t\t" + st.getDivisions().getName());
            System.out.println("----");

        }
        s.close();

    }

    public static void updateStudios() {
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Transaction t = s.beginTransaction();


        Studios st = new Studios();
        st.setId(Read.Int("Studio ID:"));
        st.setName(Read.String("Name: "));
        st.setCountry(Read.String("Country: "));
        st.setDivisions(new Divisions(Read.Int("Division ID: ")));
        s.update(st);
        t.commit();
        s.close();

    }

    public static void deleteStudios() {
        SessionFactory sf = getSessionFactory();
        Session s = sf.openSession();
        Transaction t = s.beginTransaction();
        int id = Read.Int("Type the ID of the studio to be deleted: ");
        Query q = s.createQuery("from Studios where id =" +id);
        List results = q.list();
        Iterator iterator = results.iterator();
        Studios st = (Studios) iterator.next();
        s.delete(st);
        t.commit();
        s.close();

    }


}


